---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
    exclude_paths:
    - 'app/**/*.test.js'
  eslint:
    enabled: true
    channel: eslint-3
    config:
      config: .eslintrc
  fixme:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths: []
