language: objective-c

osx_image: xcode7.3

install:
  - mkdir -p /Users/travis/build/facebook/.nvm
  - export NVM_DIR="/Users/travis/build/facebook/.nvm"
  - brew install nvm
  - source $(brew --prefix nvm)/nvm.sh
  - nvm install 5
  - npm config set spin=false
  - npm config set progress=false
  - travis_wait npm install

script:
  - if [[ "$TEST_TYPE" = objc ]]; then echo 'osx' ; fi
  - if [[ "$TEST_TYPE" = js ]]; then npm run travis -- --maxWorkers=1; fi

env:
  matrix:
    - TEST_TYPE=objc
    - TEST_TYPE=js

branches:
  only:
    - master

notifications:
  email: false
