language: node_js
node_js:
  - "6"
sudo: false
script:
  - make $JOB
notifications:
  email: false
cache:
  directories:
    - node_modules
branches:
  only:
    - master
env:
  - JOB=travis
  - JOB=ios
