language: objective-c

osx_image: xcode7.3

install:
  - mkdir -p /Users/travis/build/lededje/.nvm
  - export NVM_DIR="/Users/travis/build/lededje/.nvm"
  - brew install nvm
  - source $(brew --prefix nvm)/nvm.sh
  - nvm install 5
  - npm config set spin=false
  - npm config set progress=false
  - travis_wait npm install

script:
  - make $TEST_TYPE

env:
  matrix:
    - TEST_TYPE=ui
    - TEST_TYPE=jest

branches:
  only:
    - master

notifications:
  email: false
