language: node_js
node_js:
  - "6"
sudo: false
script:
  - ./scripts/travis.sh
notifications:
  email: false
cache:
  directories:
    - node_modules
branches:
  only:
    - master
    - /^greenkeeper/.*$/
