export const ADD_TASK = 'ADD_TASK';
export const CHANGE_FILTER_TYPE = 'CHANGE_FILTER_TYPE';
export const CHANGE_TASK_TYPE = 'CHANGE_TASK_TYPE';
export const REMOVE_TASK = 'REMOVE_TASK';
export const SET_DEFERRING_TASK = 'SET_DEFERRING_TASK';
export const CLEAR_DEFERRING_TASK = 'CLEAR_DEFERRING_TASK';
export const DEFER_TASK = 'DEFER_TASK';
export const STOP_ANIMATING = 'STOP_ANIMATING';
export const UPDATE_PERMISSIONS = 'UPDATE_PERMISSIONS';
export const CLEAN_TASKS = 'CLEAN_TASKS';

// Blacklist these from hitting storage
export const STATEFUL_ACTIONS = [CHANGE_FILTER_TYPE, SET_DEFERRING_TASK, CLEAR_DEFERRING_TASK];
