export const ADD_TASK = 'ADD_TASK';
export const CHANGE_FILTER_TYPE = 'CHANGE_FILTER_TYPE';
export const CHANGE_TASK_TYPE = 'CHANGE_TASK_TYPE';
export const CHANGE_NEXT_TASK_TYPE = 'CHANGE_NEXT_TASK_TYPE';
export const REMOVE_TASK = 'REMOVE_TASK';
export const SQUASH_TASKS = 'SQUASH_TASKS';
